package org.zerokosh.app.ui.common

// #region Imports
import android.annotation.SuppressLint
import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext
// #endregion

/**
 * §2.4/§12: display labels come from resources keyed tpl_<template>_<field>
 * (generated by spec/gen_strings.py); fallback = humanized field_id.
 */
@SuppressLint("DiscouragedApi")
fun fieldLabel(context: Context, templateId: String, fieldKey: String): String {
    val id = context.resources.getIdentifier("tpl_${templateId}_$fieldKey", "string", context.packageName)
    return if (id != 0) context.getString(id) else fieldKey.replace('_', ' ').replaceFirstChar { it.uppercase() }
}

@Composable
fun fieldLabel(templateId: String, fieldKey: String): String =
    fieldLabel(LocalContext.current, templateId, fieldKey)
