# Generates app/src/main/res/values/strings_templates.xml from spec/templates.json.
# §12: keys are tpl.<template_id>.<field_id>; Android resource names cannot
# contain dots, so dots map to underscores (DECISIONS.md D-005).
import json, pathlib

SPECIAL = {
    "ifsc": "IFSC code", "micr": "MICR code", "tpin": "TPIN", "cvv": "CVV",
    "upi_id": "UPI ID", "upi_pin": "UPI PIN", "atm_pin": "ATM PIN",
    "dp_id": "DP ID", "bo_id": "BO ID", "cdsl_tpin": "CDSL TPIN",
    "mpin": "MPIN", "ipin": "IPIN", "uan_or_pran": "UAN / PRAN",
    "api_key": "API key", "api_secret": "API secret", "mf_folios": "Mutual fund folios",
    "puk": "PUK code", "sim_pin": "SIM PIN", "totp": "One-time code (TOTP)",
    "fastag_id": "FASTag ID", "netbanking_user_id": "Net-banking user ID",
    "id_kind": "ID type", "id_number": "ID number", "name_as_per_id": "Name as per ID",
    "file_copy": "Scanned copy", "gift_cards": "Gift cards", "password_if_any": "Password (if any)",
    "wifi_password": "Wi-Fi password", "billing_cycle_day": "Billing cycle day",
    "due_day": "Bill due day", "body": "Note",
}

root = pathlib.Path(__file__).resolve().parent.parent
templates = json.loads((root / "spec" / "templates.json").read_text(encoding="utf-8-sig"))

def humanize(fid: str) -> str:
    if fid in SPECIAL:
        return SPECIAL[fid]
    return fid.replace("_", " ").capitalize()

lines = ['<?xml version="1.0" encoding="utf-8"?>',
         "<!-- GENERATED by spec/gen_strings.py from spec/templates.json - do not edit by hand -->",
         "<resources>"]
seen = set()
for t in templates["templates"]:
    tid = t["id"]
    lines.append(f'    <string name="tpl_{tid}">{humanize(tid).title() if tid != "upi" else "UPI"}</string>')
    for f in t["fields"]:
        key = f'tpl_{tid}_{f["k"]}'
        if key in seen:
            continue
        seen.add(key)
        lines.append(f'    <string name="{key}">{humanize(f["k"])}</string>')
lines.append("</resources>")
out = root / "app" / "src" / "main" / "res" / "values" / "strings_templates.xml"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out} ({len(seen)} field labels)")
